### ISSUE TITLE
Including Participant.hpp instead of precice.hpp - By design or outdated?

### ISSUE THREAD

**Issue by MakisH** [precice/rust-bindings#2]
https://github.com/precice/rust-bindings/blob/a59ec3aed727ce844a8ff4ab9e081e0b5e379372/src/precice-bridge.cpp#L5

Same as in the Python bindings: https://github.com/precice/python-bindings/issues/194

**Comment by fsimonis** [comment]
It was outdated. Closed by https://github.com/precice/rust-bindings/commit/76d0df0b9eaf49d35718296d76d662ad0de5ffc5
